### ISSUE TITLE
it gets stuck so many many many times

### ISSUE THREAD

**Issue by nurne** [git-moss/LaunchpadPro4Bitwig#1]
and takes like 30-60 seconds to release
like there's a bad loop or something that's just sleeping the whole launchpad
can't do anything with it
happens on VSTs and on native-bitwig devices alike.

thanks!

**Comment by git-moss** [comment]
Sorry, your issue somehow got lost and I noticed it just yet. Is this still a problem with the latest releases (both Bitwig and the script)?

**Comment by nurne** [comment]
hey - yeah, it's an awesome script but there are some stuckness bugs, mostly when working with heavy VSTs (like SynthMaster 2.8) - it seems like there's an infinite loop or something and then it breaks out after the system maybe stops your script and restarts it (because the launch pro makes the rainbow boot again) - what info can i extract to let you know about it more? where do i get that info from? can i turn on debug somehow?

**Comment by nurne** [comment]
@git-moss

**Comment by git-moss** [comment]
Please have a look in the script console (View -> Show Control Script Console) when that happens again and if you see any errors.
