### ISSUE TITLE
Pad buttons not working

### ISSUE THREAD

**Issue by szucs2020** [git-moss/LaunchpadPro4Bitwig#2]
My launchpad was working fine until one day, the lights didn't come on. When I restart the script, the launchpad lights blink quickly then turn off. Pressing the left/right buttons change the scale (note mode) properly, and show the model in bitwig, and many of the other side buttons work, but with no lights. The pads don't work at all, no lights, and no MIDI going to instruments. 

I've checked the settings on both the launchpad and the script manager to ensure that the MIDI channel is set correctly. I've gone as far as printing outputs in the script to ensure that its receiving the MIDI correctly from the launchpad, and it is. I've changed USB ports, reinstalled the driver and updated the firmware, and nothing fixes the issue. I'm using Windows 10 and bitwig 1.3.13. 

Also, when I use the launchpad as a generic controller, the lights and pads work fine, so I know its not my launchpad.

**Comment by git-moss** [comment]
What version of the script are you using? Which Launchpad do you have?

**Comment by szucs2020** [comment]
I have the launchpad pro, and I'm using the latest stable version of the script (1.10 I believe). I have also tried cloning the repo and using the development version, and I had the same issue.

**Comment by git-moss** [comment]
Weird. Could it be that you have modified the midi channel on the LP? Another idea would be to try to rewrite the firmware.

**Comment by szucs2020** [comment]
In bitwig, I have the in and outs set to MIDI channel 2, and on the launchpad settings, Ive selected the second light for MIDI output, though I have experimented with different ones as well. Is that configuration correct? I will try to reinstall the firmware.

**Comment by git-moss** [comment]
What you select in Bitwig is the port, not the midi channel. You need to select the 2nd port, which should be correct in your settings. The Launchpad needs to be set to midi channel 1!

**Comment by szucs2020** [comment]
Finally, it works! It took a combination of changing the midi channel to 1, reinstalling drivers / firmware and removing the USB extension to get it to work. thanks for the help!

**Comment by git-moss** [comment]
Great!
